Add a unified TLS stream type (fixes #46)
quininer/tokio-rustls pull request #47
Opened 2019-09-17 08:20 UTC by djc

2019-09-17 09:10 UTC, quininer requested changes

2019-09-17 09:10 UTC, quininer commented on src/lib.rs
> +    pub fn get_io_mut(&mut self) -> &T {
```suggestion
    pub fn get_io_mut(&mut self) -> &mut T {
```

2019-09-17 09:10 UTC, quininer commented on src/lib.rs
> +impl<T> TlsStream<T> {
We can also add `get_session` and `get_session_mut`.

```rust
fn get_session(&self) -> &dyn Session;

fn get_session_mut(&mut self) -> &mut dyn Session;
```

2019-09-17 09:33 UTC, djc commented on src/lib.rs
> +    pub fn get_io_mut(&mut self) -> &T {
Did a slightly different take, have a look.

2019-09-17 09:33 UTC, djc commented on src/lib.rs
> +impl<T> TlsStream<T> {
Ahh, trait objects. Should have thought of that.

2019-09-17 11:39 UTC, quininer approved these changes
LGTM, Thanks you!

2019-09-17 11:39 UTC, merged

2019-09-17 12:36 UTC, djc commented
Would you mind pushing out 0.10.1 to crates.io? Then I can remove this code from my downstream project. :)

2019-09-17 13:55 UTC, quininer commented
`0.10.1` has been released!

2019-09-17 18:50 UTC, djc commented
Thank you!

2019-09-19 14:25 UTC, djc commented
FYI, I just noticed on someone else's machine that this inadvertently introduced a dependency on Rust 1.37.0 due to the use of `Self::Client` and `Self::Server` for enum variants. Not sure if you have MSRV policy or anything, but just so you're aware.

2019-09-19 14:43 UTC, quininer commented
I don't have an MSRV policy, but I don't mind supporting more versions of rustc.